### PR TITLE
Backporting #55 to ognl-3-1-x branch.

### PR DESCRIPTION
**Pull request by harawata**
getDeclaredMethods() should search super-interfaces recursively.

### CODE REVIEW

**Comment by harawata** [comment]
I noticed that 3.1.x still uses `Introspector#getBeanInfo()` in `getReadMethod()` (i.e. #33 was not backported).
So, the following tests will fail.

```java
// In Java8Test
Method method = OgnlRuntime.getReadMethod(ClassWithDefaults.class, "defaultMethod");
assertNotNull(method);
Method method = OgnlRuntime.getReadMethod(SubClassWithDefaults.class, "defaultMethod");
assertNotNull(method);
```
I am going to fix this in the next PR.

**Comment by lukaszlenart** [comment]
I assume it's ready, right?

**Comment by harawata** [comment]
I believe it is, yes. :)

**Comment by lukaszlenart** [comment]
LGTM 👍

**Pull request merged**
