### PR TITLE
Cache clearing enhancement (clear additional cache, synchronization fix):

### PR DESCRIPTION
**Pull request by JCgH4164838Gh792C124B5**
Attempt to resolve issue #34:
- Add a clearAdditionalCache() method to clear some additional cache elements.
Using a separate method as changing the behaviour of clearCache() could negatively impact existing usage.
- Added missing synchronization within clearCache() for many elements that should have synchronization for modifications.

### CODE REVIEW

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello OGNL Team.

After reviewing open issues, decided to try to replicate issue #42 and was able to confirm that it still exists.  A new test confirmed the syserr output was occurring for the reported scenario but the actual call by OGNL worked just fine.

Looking at the code and "forcing both paths" (abstract and concrete) the proper result was returned in both cases.  So the `OgnlRuntime.findBestMethod()` in this PR has now been updated with checks so that it will not output the error anymore unless _both_ methods being compared have the _same "concreteness" or "abstractness"_ - since that would definitely be a weird state that should be reported.

**Comment by JCgH4164838Gh792C124B5** [comment]
I also encountered some weird behaviour for some of the Security Sandbox tests when performing interactive debugging for the last update to this PR. 

Occasionally one of the sandbox tests `TestOgnlRuntime.test_Call_Method_In_JDK_Sandbox_Privileged()`)
failed due to the cause being a `NullPointerException` instead of the expected type.

Running the test module outside of the debugger never produced failures, so it's unclear if it was just interference by the IDE debugger or some underlying condition in the logic.  Just wanted to leave a note for future reference in case an issue pops up.

**Comment by lukaszlenart** [comment]
@JCgH4164838Gh792C124B5 conflict :(

**Comment by JCgH4164838Gh792C124B5** [comment]
Hello @lukaszlenart .

Manual resolution of merge conflicts completed (but might conflict if #75 is accepted/merged).
Additional commit to use source/target 1.6 was required to get Travis CI checks to complete (just like in #75).

It should be easier for others to review now, at least. :smile:

**Comment by lukaszlenart** [comment]
LGTM 👍

**Pull request merged**
