### PR TITLE
[OGNL-102] Improves performance when null was returned

### PR DESCRIPTION
**Pull request by lukaszlenart**
Improves performance of chained expressions in case if the `root` is `null`

Refs [OGNL-102](https://issues.apache.org/jira/browse/OGNL-102)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
@davoustp @harawata @quaff could you take a look? this should improve performance a bit, it's in relation to https://github.com/jkuhnert/ognl/pull/138 and the JIRA ticket.

**Comment by harawata** [comment]
Hi @lukaszlenart ,

I'm sorry about the slow response (as always)!

So, is `root` the only concern here?

With the following test, for example, the for-loop is still evaluated for the second node and the similar exception is thrown :

> ognl.OgnlException: source is null for getProperty(null, "key2")

```java
public void testNullHnadling() throws Exception {
  OgnlContext context = (OgnlContext) Ognl.createDefaultContext(null, new DefaultMemberAccess(false));
  Map<String, Object> root = new HashMap<>();
  root.put("key1", null);
  String expr = "key1.key2.key3";
  assertNull(Ognl.getValue(expr, context, root));
}
```

**Comment by lukaszlenart** [comment]
Right, but if I did that on `children` level in the `for` loop a lot of tests have started to fail, especially this [one](https://github.com/jkuhnert/ognl/pull/140/files#diff-92ad2bf9f492a4e873133771bba1a612cc41d56bcb8d7651b37ca2ec689cdd0aR71-R76)

**Comment by harawata** [comment]
Yes, it will change the designed behavior and @davoustp seems to be [aware](https://github.com/apache/struts/pull/504#issuecomment-968289949).

I'll just show some tests that emphasizes the difference in behavior.
If these results match @davoustp 's expectation, this PR should be fine.

```java
public void testNullValue() throws Exception {
  OgnlContext context = (OgnlContext) Ognl.createDefaultContext(null, new DefaultMemberAccess(false));
  Map<String, Object> root = new HashMap<>();
  root.put("key1", null);
  String expr = "key1.key2.key3";
  assertNull(Ognl.getValue(expr, context, root)); // FAIL : OgnlException
}

public void testEmptyRoot() throws Exception {
    OgnlContext context = (OgnlContext) Ognl.createDefaultContext(null, new DefaultMemberAccess(false));
    Map<String, Object> root = new HashMap<>();
    String expr = "key1.key2.key3";
    assertNull(Ognl.getValue(expr, context, root)); // FAIL : OgnlException
}

public void testNullRoot() throws Exception {
    OgnlContext context = (OgnlContext) Ognl.createDefaultContext(null, new DefaultMemberAccess(false));
    Map<String, Object> root = null;
    String expr = "key1.key2.key3";
    assertNull(Ognl.getValue(expr, context, root)); // PASS
}
```

**Comment by lukaszlenart** [comment]
Changes will be moved into #155

**Pull request closed without merging**
