### PR TITLE
Allow override a strategy for loading Class on DefaultClassResolver

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I will propose to allow override a strategy for loading Class. Actually, the MyBatis core module want to override strategy using this extending point. Currently, we copy the `DefaultClassResolver` and modify a class loading logic.

WDYT?

### CODE REVIEW

**Comment by lukaszlenart** [comment]
👍

**Comment by lukaszlenart** [comment]
Should I release 3.2.6?

**Comment by kazuki43zoo** [comment]
Yes! I wait to release 3.2.6 👍

**Comment by lukaszlenart** [comment]
under way to the Central

**Pull request merged**
